language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install devscripts equivs build-essential python-pip
  - sudo mk-build-deps -i -r
  - sudo apt-get install -f
script:
  - debuild -i -us -uc -b
